//GIT-VS-VERSION-GEN.bat generated resource header.
#define GEN_VER_VERSION_STRING   "1.0.0.23\0" 
#define GEN_VER_DIGITAL_VERSION  1,0,0,23
#define GEN_VER_VERSION_HEX      0x0001000000000000 
#define GEN_VER_COMMENT_STRING   "Release Candidate 0\0" 
#define GEN_VER_PRIVATE_FLAG     0 
#define GEN_VER_PRIVATE_STRING   "\0" 
#define GEN_VER_PATCHED_FLAG     VS_FF_PATCHED 
#define GEN_VER_PRERELEASE_FLAG  VS_FF_PRERELEASE 
